server:
  port: 9900

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

spring.data.mongodb.uri: mongodb://mongodb:27017/operation